project:
  type: website
  output-dir: docs

website:
  title: "Dataviz Anilom"
  site-url: https://anabellanilom.github.io/Dataviz/ 

  navbar:
    left:
      - href: index.qmd
      - href: dataviz.qmd
      - href: biblio.qmd
    right:
      - icon: github
        href: https://github.com/anabellanilom
      - text: "{{< ai google-scholar >}}"
        href: "https://scholar.google.com/citations?user=KLz7F4IAAAAJ&hl=es"
        target: _blank
        rel: me
      - text: "{{< ai orcid >}}"
        href: "https://orcid.org/0000-0001-7394-8589"
        target: _blank
        rel: me
      - icon: linkedin
        href: https://www.linkedin.com/in/draanabellamolina
        target: _blank
        rel: me
      - icon: envelope
        href: mailto:anabella.anilom@gmail.com

  twitter-card:
    card-style: summary_large_image
    image: "images/social-card.png"
    creator: "@ananilom"

  page-footer:
    left: "Â© 2025 Anabella Molina. Contenido bajo licencia <a href='https://creativecommons.org/licenses/by-nc/4.0/'>CC BY-NC 4.0</a>"
    center: "Hecho con [Quarto](https://quarto.org)"
    right: "Alojado en [GitHub Pages](https://pages.github.com)"

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: es
      text: "ES"
    - name: en
      text: "EN"
  mainlanguage: "es"
  languages: ["en"]

lang: es

format:
  html:
    css: styles.css
    theme: cosmo
    toc: true

